name: GitHub Actions Demo2
on: 
  workflow_run:
    workflows: ["GitHub Actions Demo"]
    types: [completed]

jobs:
  two:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"